### ISSUE TITLE
mudefarm is not claiming

### ISSUE THREAD

**Issue by levirod** [chiyadev/MudaeFarm#184]
My mudefarm is not claiming, how can I fix it? Here are some screenshots of my settings.

![Screenshot_13](https://user-images.githubusercontent.com/49394440/86410944-c7fcdb00-bc89-11ea-8e74-75736b406ce7.png)
![Screenshot_14](https://user-images.githubusercontent.com/49394440/86410947-c92e0800-bc89-11ea-8d7c-9344dcb50a7d.png)
![Screenshot_15](https://user-images.githubusercontent.com/49394440/86410949-c9c69e80-bc89-11ea-909c-7b3a68a16dc4.png)
![Screenshot_16](https://user-images.githubusercontent.com/49394440/86410952-c9c69e80-bc89-11ea-811b-1b47ae284360.png)
![Screenshot_17](https://user-images.githubusercontent.com/49394440/86410954-ca5f3500-bc89-11ea-9945-a573e8259066.png)

**Comment by levirod** [comment]
Thanks, i tried this on a server that i created and it worked, i will try now on another.

**Comment by RedCon329** [comment]
@joshoea how do you turn off kakera claiming without turning off waifu/husbando claims?

![image](https://user-images.githubusercontent.com/68579011/89122475-ffb1a980-d4f9-11ea-9412-e941602c872e.png)

i want to turn off mine since its so buggy right now that it auto claims even though "kakera_ignore_cooldown" is set to false. it spams the server everytime there is a kakera rolled.

**Comment by phosphene47** [comment]
@RedCon329 You can remove all kakera targets like `"kakera_targets": []`.
