### ISSUE TITLE
Custom reaction emotes 

### ISSUE THREAD

**Issue by mathias0903** [chiyadev/MudaeFarm#48]
some servers use custom reaction emotes. which means that the check for if the reaction is a heart emote always returns false.
im assuming this is how you differentiate between info marry and rolls.
it will either need to be done diffrently or have some way to easily add new emojis that it can be.
or maybe instead of checking if its a heart emojis, check if its not one of the 2 page shifting emojis which there currently aren't anyway of changing.

**Comment by phosphene47** [comment]
I think it will be more future-proof to check for hearts rather than check for non-hearts.

**Comment by mathias0903** [comment]
sorry english is my second Language so i might not have explanied the problem proper.
Mudae bot allows to use/add custom reacts for rolls with "$customreact", so if someone uses that, it won't be hearts on rolls but something else like thumbup or something. it can even be custom emotes unique to that server. which means with the current system, it won't work on those servers. since the react for rolls is not a heart and therefor not recognized as a roll by MudaeFarm. 
so a way to add emotes to the list of emotes it can be for rolls would be nice

**Comment by mathias0903** [comment]
i been looking through the code. and found that you already have a check for if something is the $im command
` // message must not be $im
if (_imFooterRegex.IsMatch(embed.Footer.Value.Text))
    return; }`
so i don't see why you need to check if something is a heart emoji. wouldn't work just find if it just reacted to the first emote on a roll

**Comment by phosphene47** [comment]
It's always good to have an extra safety measure in place, to check for a heart emoji before reacting. Mudae's output format can change anytime.

Having said that, it would greatly simplify the configuration if we reacted to the first emote rather than requiring every custom emote be added to config.

It would be ideal to check for hearts by default and allow a guild-level configuration override to disable the check and allow custom emotes.
